apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: my-mongodb
  namespace: everest
spec:
  backup:
    enabled: false
    # schedules:
    # - backupStorageName: s3
    #   enabled: true
    #   name: my-backup-schedule
    #   schedule: 55 * * * *
  engine:
    replicas: 3
    resources:
      cpu: "1"
      memory: 1G
    storage:
      class: standard-rwo
      size: 5Gi
    type: psmdb
    version: 7.0.14-8
  monitoring:
    resources: {}
