apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: mongodb-basic
  namespace: everest
spec:
  backup:
    enabled: false
    # pitr:
    #   backupStorageName: s3
    #   enabled: true
    schedules:
    - backupStorageName: s3
      enabled: true
      name: my-backup-schedule
      schedule: 53 * * * *
  engine:
    replicas: 3
    resources:
      cpu: "1"
      memory: 4G
    storage:
      class: standard-rwo
      size: 5Gi
    type: psmdb
    version: 7.0.14-8
