apiVersion: everest.percona.com/v1alpha1
kind: DatabaseClusterRestore
metadata:
  name: my-mongodb-restore
  namespace: everest
  labels:
    clusterName: my-mongodb
spec:
  dataSource:
    dbClusterBackupName: my-mongodb-backup
  dbClusterName: my-mongodb
